# numpy基础

### 七月在线python数据分析基础课 

褚则伟 zeweichu@gmail.com

## Numpy简介

- Numpy是Python语言的一个library [numpy](http://www.numpy.org/)
- Numpy主要支持矩阵操作和运算
- Numpy非常高效，core代码由C语言写成
- 我们第三课要讲的pandas也是基于Numpy构建的一个library
- 现在比较流行的机器学习框架（例如Tensorflow/PyTorch等等），语法都与Numpy比较接近

## 目录
- 数组简介和数组的构造(ndarray)
- 数组取值和赋值
- 数学运算
- broadcasting
- 逻辑运算
- 数组高级操作
- 文件输入输出
- 随堂小项目：用Numpy写一个Softmax

python里面调用一个包，用import对吧, 所以我们import `numpy` 包:

In [2]:
import numpy as np

## Arrays/数组

### 七月在线python数据分析班 2017升级版 julyedu.com

看你数组的维度啦，我自己的话比较简单粗暴，一般直接把1维数组就看做向量/vector，2维数组看做2维矩阵，3维数组看做3维矩阵...

可以调用np.array去从list初始化一个数组:

In [3]:
a = np.array([1, 2, 3])  # 1维数组
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # 重新赋值
print(a)            

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])   # 2维数组
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
print(b.shape)  #可以看形状的（非常常用！！！）                  
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


我们可以用dtype来看numpy数组中元素的类型:

In [6]:
b.dtype

dtype('int64')

ndim查看numpy ndarray的维度

In [7]:
b.ndim

2

有一些内置的创建数组的函数:

In [8]:
a = np.zeros((2,2))  # 创建2x2的全0数组
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [9]:
b = np.ones((1,2))   # 创建1x2的全1数组
print(b)

[[ 1.  1.]]


In [10]:
c = np.full((2,2), 7) # 定值数组
print(c) 

[[7 7]
 [7 7]]


In [11]:
d = np.eye(2)        # 对角矩阵（对角元素为1）
print(d)

[[ 1.  0.]
 [ 0.  1.]]


In [12]:
e = np.random.random((2,2)) # 2x2的随机数组(矩阵)
print(e)

[[ 0.84387981  0.4407905 ]
 [ 0.01786365  0.73172481]]


In [14]:
f = np.empty((2,3,2)) # empty是未初始化的数据
print(f)
print(f.shape)

[[[ -2.00000000e+000   3.11109886e+231]
  [  2.96439388e-323   0.00000000e+000]
  [  0.00000000e+000   1.16096346e-028]]

 [[  1.04857803e-142   1.16467185e-028]
  [  6.03395497e-154   8.09280208e-153]
  [  5.55993283e+141   8.34403734e-309]]]
(2, 3, 2)


In [15]:
g = np.arange(15) # 用arange可以生成连续的一串元素
print(g)
print(g.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)


数组可以有不同的数据类型

生成数组时可以指定数据类型，如果不指定numpy会自动匹配合适的类型

In [16]:
arr = np.array([1,2,3], dtype=np.float64)
print(arr.dtype)

float64


In [17]:
arr = np.array([1,2,3], dtype=np.int32)
print(arr.dtype)

int32


In [24]:
arr = np.array([1,2,3], dtype=np.complex)
print(arr)
print(arr.dtype)

[ 1.+0.j  2.+0.j  3.+0.j]
complex128


linspace可以等间距地生成一组数据

In [29]:
np.linspace(0, 3, 13)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,
        2.25,  2.5 ,  2.75,  3.  ])

In [33]:
x = np.linspace(0, 2*np.pi, 100)
sinx = np.sin(x)
# sinx

使用astype复制数组并转换数据类型

In [18]:
int_arr = np.array([1,2,3,4,5])
float_arr = int_arr.astype(np.float)
print(int_arr.dtype)
print(float_arr.dtype)

int64
float64


使用astype将float转换为int时小数部分被舍弃

In [19]:
float_arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
int_arr = float_arr.astype(dtype = np.int)
print(int_arr)

[ 3 -1 -2  0 12 10]


使用astype把字符串转换为数组，如果失败抛出异常。

In [20]:
str_arr = np.array(['1.25', '-9.6', '42'], dtype = np.string_)
float_arr = str_arr.astype(dtype = np.float)
print(float_arr)

[  1.25  -9.6   42.  ]


astype使用其它数组的数据类型作为参数

In [21]:
int_arr = np.arange(10)
float_arr = np.array([.23, 0.270, .357, 0.44, 0.5], dtype = np.float64)
print(int_arr.astype(float_arr.dtype))
print(int_arr[0], int_arr[1])

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
0 1


reshape这个function可以改变ndarray的形状，只要总的element数量不变就OK了

In [34]:
a = np.arange(12).reshape(3,4)
a.shape

(3, 4)

In [35]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

如果一个ndarray的数据量太大，print的时候中间的一些数据会被省略

In [40]:
a = np.arange(5000).reshape(50,10,10)
a

array([[[   0,    1,    2, ...,    7,    8,    9],
        [  10,   11,   12, ...,   17,   18,   19],
        [  20,   21,   22, ...,   27,   28,   29],
        ..., 
        [  70,   71,   72, ...,   77,   78,   79],
        [  80,   81,   82, ...,   87,   88,   89],
        [  90,   91,   92, ...,   97,   98,   99]],

       [[ 100,  101,  102, ...,  107,  108,  109],
        [ 110,  111,  112, ...,  117,  118,  119],
        [ 120,  121,  122, ...,  127,  128,  129],
        ..., 
        [ 170,  171,  172, ...,  177,  178,  179],
        [ 180,  181,  182, ...,  187,  188,  189],
        [ 190,  191,  192, ...,  197,  198,  199]],

       [[ 200,  201,  202, ...,  207,  208,  209],
        [ 210,  211,  212, ...,  217,  218,  219],
        [ 220,  221,  222, ...,  227,  228,  229],
        ..., 
        [ 270,  271,  272, ...,  277,  278,  279],
        [ 280,  281,  282, ...,  287,  288,  289],
        [ 290,  291,  292, ...,  297,  298,  299]],

       ..., 
       [[4700, 4701, 

## Array indexing/数组取值和赋值

### 七月在线python数据分析基础课

Numpy提供了蛮多种取值的方式的.

可以像list一样切片（多维数组可以从各个维度同时切片）:

In [203]:
import numpy as np

# 创建一个如下格式的3x4数组
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 在两个维度上分别按照[:2]和[1:3]进行切片，取需要的部分
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print b

[[2 3]
 [6 7]]


虽然，怎么说呢，不建议你这样去赋值，但是你确实可以修改切片出来的对象，然后完成对原数组的赋值.

In [13]:
print(a[0, 1])  
b[0, 0] = 77    # b[0, 0]改了，很遗憾a[0, 1]也被修改了
print(a[0, 1])

0.0
0.0


创建3x4的2维数组/矩阵

In [3]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


你就放心大胆地去取你想要的数咯:

In [15]:
row_r1 = a[1, :]    # 第2行，但是得到的是1维输出（列向量）
row_r2 = a[1:2, :]  # 1x2的2维输出
row_r3 = a[[1], :]  # 同上
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


试试在第2个维度上切片也一样的:

In [4]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


下面这个高级了，更自由地取值和组合，但是要看清楚一点:

In [18]:
a = np.array([[1,2], [3, 4], [5, 6]])

# 其实意思就是取(0,0),(1,1),(2,0)的元素组起来
print(a[[0, 1, 2], [0, 1, 0]])

# 下面这个比较直白啦
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [19]:
# 再来试试
print(a[[0, 0], [1, 1]])

# 还是一样
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


再来熟悉一下

先创建一个2维数组

In [41]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


用下标生成一个向量

In [42]:
b = np.array([0, 2, 0, 1])

你能看明白下面做的事情吗？

In [43]:
print(a[np.arange(4), b]) 

[ 1  6  7 11]


In [45]:
a[[0,1,2,3], b]

array([ 1,  6,  7, 11])

既然可以取出来，我们当然也可以对这些元素操作咯

In [11]:
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


比较fashion的取法之一，用条件判定去取（但是很好用）:

In [46]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # 就是判定一下是否大于2

print(bool_idx)  # 返回一个布尔型的3x2数组

[[False False]
 [ True  True]
 [ True  True]]


用刚才的布尔型数组作为下标就可以去除符合条件的元素啦(Boolean indexing)

In [47]:
print(a[bool_idx])

[3 4 5 6]


其实一句话也可以完成是不是？

In [48]:
print(a[a > 2])

[3 4 5 6]


其实还有很多细节，其他的方式去取值，你可以看看官方文档。

我们一起来来总结一下，看下面切片取值方式（对应颜色是取出来的结果）：

![](http://old.sebug.net/paper/books/scipydoc/_images/numpy_intro_02.png)
![](http://old.sebug.net/paper/books/scipydoc/_images/numpy_intro_03.png)

更多的内容可以读读[文档](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).