# numpy operations
## 数学运算
### 七月在线python数据分析基础课

In [1]:
import numpy as np

下面这些运算才是你在科学运算中经常经常会用到的，比如逐个元素的运算如下:

In [18]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

逐元素求和有下面2种方式

In [3]:
print(x + y)
print(np.add(x, y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


逐元素作差

In [4]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


逐元素相乘

In [5]:
print(x * y)
print(np.multiply(x, y))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


逐元素相除

In [6]:
print(x / y)
print(np.divide(x, y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


逐元素求平方根！！！

In [9]:
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


还有一些更加高级的Functions，例如sin, cos, exp也可以用numpy来做

In [16]:
z = np.linspace(0, 2*np.pi, 13)
np.sin(z)

array([  0.00000000e+00,   5.00000000e-01,   8.66025404e-01,
         1.00000000e+00,   8.66025404e-01,   5.00000000e-01,
         1.22464680e-16,  -5.00000000e-01,  -8.66025404e-01,
        -1.00000000e+00,  -8.66025404e-01,  -5.00000000e-01,
        -2.44929360e-16])

In [17]:
np.cos(z)

array([  1.00000000e+00,   8.66025404e-01,   5.00000000e-01,
         6.12323400e-17,  -5.00000000e-01,  -8.66025404e-01,
        -1.00000000e+00,  -8.66025404e-01,  -5.00000000e-01,
        -1.83697020e-16,   5.00000000e-01,   8.66025404e-01,
         1.00000000e+00])

In [12]:
np.exp(np.arange(5))

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

那如果我要做矩阵的乘法运算怎么办！！！恩，别着急，照着下面写就可以了:

[matrix multiplication](http://mathworld.wolfram.com/MatrixMultiplication.html)

In [13]:
v = np.array([9,10])
w = np.array([11, 12])

求向量内积

```dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])```

In [14]:
print(v.dot(w))
print(np.dot(v, w))

219
219


矩阵的乘法

In [19]:
print(x.dot(v))
print(np.dot(x, v))

[ 29.  67.]
[ 29.  67.]


In [20]:
print(x.dot(y))
print(np.dot(x, y))

[[ 19.  22.]
 [ 43.  50.]]
[[ 19.  22.]
 [ 43.  50.]]


转置和数学公式一样，简单粗暴

In [21]:
print(x)
print(x.T)

[[ 1.  2.]
 [ 3.  4.]]
[[ 1.  3.]
 [ 2.  4.]]


In [ ]:
需要说明一下，1维的vector转置还是自己

In [22]:
v = np.array([1,2,3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]


2维的就不一样了

In [23]:
w = np.array([[1,2,3]])
print(w)
print(w.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


利用转置矩阵做dot product

In [25]:
arr = np.random.randn(6,3)
print(np.dot(arr.T, arr))

[[ 1.10936754  1.03698267 -0.04091061]
 [ 1.03698267  1.61283468 -0.00482529]
 [-0.04091061 -0.00482529  2.00147109]]


In [26]:
print(np.dot(arr, arr))

ValueError: shapes (6,3) and (6,3) not aligned: 3 (dim 1) != 6 (dim 0)

高维的tensor可以用transpose和swapaxes来做转置

In [28]:
arr = np.arange(16).reshape((2, 2, 4))
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [29]:
print(arr.transpose((1,0,2)))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [30]:
print(arr.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


[matmul](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.matmul.html) 矩阵乘法

Matrix product of two arrays.

The behavior depends on the arguments in the following way.

- If both arguments are 2-D they are multiplied like conventional matrices.
- If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly.
- If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed.
- If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.

In [31]:
x = np.arange(24).reshape(2,3,4)
y = np.arange(8).reshape(4,2)
print(np.matmul(x,y))

[[[ 28  34]
  [ 76  98]
  [124 162]]

 [[172 226]
  [220 290]
  [268 354]]]


In [36]:
print(np.dot(x, y))

[[[ 28  34]
  [ 76  98]
  [124 162]]

 [[172 226]
  [220 290]
  [268 354]]]


In [34]:
x1 = np.arange(12).reshape(3,4)
print(np.matmul(x1, y))
x2 = np.arange(12,24).reshape(3,4)
print(np.matmul(x2, y))

[[ 28  34]
 [ 76  98]
 [124 162]]
[[172 226]
 [220 290]
 [268 354]]


In [25]:
y = np.arange(16).reshape(2,4,2)
print(x.dot(y).shape)

(2, 3, 2, 2)


In [26]:
print(np.matmul(x,y).shape)

(2, 3, 2)


你猜你做科学运算会最常用到的矩阵内元素的运算是什么？对啦，是求和，用 `sum`可以完成:

In [21]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # 数组/矩阵中所有元素求和; prints "10"
print(np.sum(x, axis=0))  # 按行去求和; prints "[4 6]"
print(np.sum(x, axis=1))  # 按列去求和; prints "[3 7]"

10
[4 6]
[3 7]


求平均的函数写法与求和非常类似

In [20]:
print(np.mean(x))
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))
print(x.cumsum(axis=0))
print(x.cumprod(axis=1))

2.5
[ 2.  3.]
[ 1.5  3.5]
[[1 2]
 [4 6]]
[[ 1  2]
 [ 3 12]]


In [22]:
print(np.mean(x))
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))
print(x.cumsum(axis=0))
print(x.cumprod(axis=1))

2.5
[ 2.  3.]
[ 1.5  3.5]
[[1 2]
 [4 6]]
[[ 1  2]
 [ 3 12]]


还有一些其他我们可以想到的运算，比如求和，求平均，求cumulative sum，sumulative product用numpy都可以做到

我想说最基本的运算就是上面这个样子，更多的运算可能得查查[文档](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

其实除掉基本运算，我们经常还需要做一些操作，比如矩阵的变形，转置和重排等等:

一维数组的排序

In [20]:
arr = np.random.randn(8)
print(arr)
arr.sort()
print(arr)

[ 0.70150419 -0.88493701  0.37449618 -0.42676191  1.52654468 -1.79515205
  0.05635219  0.80712566]
[-1.79515205 -0.88493701 -0.42676191  0.05635219  0.37449618  0.70150419
  0.80712566  1.52654468]


二维数组也可以在某些维度上排序

In [21]:
arr = np.random.randn(5,3)
print(arr)
arr.sort(1)
print(arr)

[[-0.51135747 -0.0355637   0.38398028]
 [-1.44309081  1.31425286  0.16295143]
 [-0.54112556 -1.07293118  0.55690543]
 [ 0.55382507  0.79843566 -1.29064181]
 [ 0.69978121  0.24467205  0.13107927]]
[[-0.51135747 -0.0355637   0.38398028]
 [-1.44309081  0.16295143  1.31425286]
 [-1.07293118 -0.54112556  0.55690543]
 [-1.29064181  0.55382507  0.79843566]
 [ 0.13107927  0.24467205  0.69978121]]


下面我们做一个小案例，找出排序后位置在5%的数字

In [22]:
large_arr = np.random.randn(1000)
large_arr.sort()
print(large_arr[int(0.05*len(large_arr))])

-1.65535730932


如何找出最大的top k elements的index呢？

In [35]:
arr = np.arange(12)
np.random.shuffle(arr)
arr

array([ 1,  7,  6,  2, 10,  9,  4, 11,  5,  3,  0,  8])

In [36]:
arr.argsort()[-3:][::-1]

array([7, 4, 5])

## Broadcasting
### 七月在线python数据分析基础课

这个没想好哪个中文词最贴切，我们暂且叫它“传播吧”:<br>
作用是什么呢，我们设想一个场景，如果要用小的矩阵去和大的矩阵做一些操作，但是希望小矩阵能循环和大矩阵的那些块做一样的操作，那急需要Broadcasting啦

我们要做一件事情，给x的每一行都逐元素加上一个向量，然后生成y

In [26]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # 生成一个和x维度一致的空数组/矩阵
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


比较粗暴的方式是，用for循环逐个相加

In [27]:
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


这种方法当然可以啦，问题是不高效嘛，如果你的x矩阵行数非常多，那就很慢的咯:

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

因为broadcasting的存在，你上面的操作可以简单地汇总成一个求和操作

In [24]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


当操作两个array时，numpy会逐个比较它们的shape，在下述情况下，两arrays会兼容和输出broadcasting结果：<br>

1. 相等
2. 其中一个为1，（进而可进行拷贝拓展已至，shape匹配）

比如求和的时候有：
```python
Image (3d array):  256 x 256 x 3
Scale (1d array):              3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  15 x 3 x 5
B      (1d array):  15 x 1 x 5
Result (2d array):  15 x 3 x 5
```

下面是一些 broadcasting 的例子:

我们来理解一下broadcasting的这种用法

先把v变形成3x1的数组/矩阵，然后就可以broadcasting加在w上了:

In [25]:
v = np.array([1,2,3])  # v 形状是 (3,)
w = np.array([4,5])    # w 形状是 (2,)

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


那如果要把一个矩阵的每一行都加上一个向量呢

In [41]:
x = np.array([[1,2,3], [4,5,6]])
v = np.array([1,2,3])
print(x + v)

[[2 4 6]
 [5 7 9]]


In [42]:
x = np.array([[1,2,3], [4,5,6]]) # 2x3的
w = np.array([4,5])    # w 形状是 (2,)

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


上面那个操作太复杂了，其实我们可以直接这么做嘛

In [43]:
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


broadcasting当然可以逐元素运算了

In [44]:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


总结一下broadcasting，可以看看下面的图：<br>
![](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

## 逻辑运算
### 七月在线python数据分析班 2017升级版 julyedu.com

In [92]:
x_arr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_arr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
print(np.where(cond, x_arr, y_arr))

[ 1.1  2.2  1.3  1.4  2.5]


In [94]:
arr = np.random.randn(4,4)
print(arr)

[[-1.07862334 -0.65839352 -1.13926498 -0.41236049]
 [-0.01210289  0.66752415 -0.60377733  0.59145772]
 [-0.57474232 -0.72783899 -1.45942297 -0.84187951]
 [-0.3159666   0.04350397 -0.09691279 -1.56976571]]


In [95]:
print(np.where(arr > 0, 2, -2))

[[-2 -2 -2 -2]
 [-2  2 -2  2]
 [-2 -2 -2 -2]
 [-2  2 -2 -2]]


In [97]:
print(np.where(arr > 0, 2, arr))

[[-1.07862334 -0.65839352 -1.13926498 -0.41236049]
 [-0.01210289  2.         -0.60377733  2.        ]
 [-0.57474232 -0.72783899 -1.45942297 -0.84187951]
 [-0.3159666   2.         -0.09691279 -1.56976571]]


In [102]:
cond_1 = np.array([True, False, True, True, False])
cond_2 = np.array([False, True, False, True, False])
result = np.where(cond_1 & cond_2, 0, \
          np.where(cond_1, 1, np.where(cond_2, 2, 3)))
print(result)

[1 2 1 0 3]


In [107]:
arr = np.random.randn(10)
print(arr)
print((arr > 0).sum())

[ 0.27350655 -1.51093462  0.26835915 -0.45991855  1.34450904 -1.86871203
  0.04308971  1.69640444 -0.02191351 -0.43875275]
5


In [109]:
bools = np.array([False, False, True, False])
print(bools.any()) # 有一个为True则返回True
print(bools.all()) # 有一个为False则返回False

True
False
